---
- name: Configurar servidor de monitoreo Prometheus y Grafana
  hosts: monitor
  become: yes

  tasks:
    - name: Actualizar repos
      apt:
        update_cache: yes

    - name: Instalar Prometheus
      apt:
        name:
          - prometheus
        state: present

    - name: Agregar clave GPG de Grafana
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Agregar repositorio de Grafana
      apt_repository:
        repo: "deb https://packages.grafana.com/oss/deb stable main"
        state: present

    - name: Actualizar repos despu√©s de agregar Grafana
      apt:
        update_cache: yes

    - name: Instalar Grafana
      apt:
        name: grafana
        state: present

    - name: Habilitar y arrancar servicio Prometheus
      service:
        name: prometheus
        state: started
        enabled: yes

    - name: Habilitar y arrancar servicio Grafana
      service:
        name: grafana-server
        state: started
        enabled: yes
