---
- name: Configurar servidor web Nginx
  hosts: web
  become: yes

  tasks:
    - name: Actualizar repos
      apt:
        update_cache: yes

    - name: Instalar Nginx
      apt:
        name: nginx
        state: present

    - name: Habilitar y arrancar servicio Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Asegurar carpeta del sitio Nginx
      file:
        path: /var/www/html
        state: directory
        owner: www-data
        group: www-data
        mode: "0755"

    - name: Copiar sitio est√°tico a Nginx
      copy:
        src: files/sitio_web/
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: "0644"

    - name: Crear endpoint stub_status
      copy:
        dest: /etc/nginx/conf.d/stub_status.conf
        content: |
          server {
            listen 8081;
            location /stub_status {
              stub_status;
              allow 192.168.50.11;
              allow 127.0.0.1;
              deny all;
            }
          }

    - name: Reiniciar Nginx
      service:
        name: nginx
        state: restarted
