---
- name: Instalar Node Exporter en ambas VMs
  hosts: all
  become: yes

  vars:
    node_exporter_version: "1.7.0"

  tasks:
    - name: Descargar Node Exporter
      ansible.builtin.get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
        dest: /tmp/node_exporter.tar.gz

    - name: Extraer Node Exporter
      ansible.builtin.unarchive:
        src: /tmp/node_exporter.tar.gz
        dest: /usr/local/bin/
        remote_src: yes

    - name: Renombrar carpeta extra√≠da
      ansible.builtin.command:
        cmd: mv /usr/local/bin/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter /usr/local/bin/node_exporter
      args:
        removes: /usr/local/bin/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter

    - name: Crear archivo de servicio systemd para Node Exporter
      ansible.builtin.copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=Node Exporter
          After=network.target

          [Service]
          ExecStart=/usr/local/bin/node_exporter
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Recargar systemd
      ansible.builtin.command: systemctl daemon-reload

    - name: Iniciar y habilitar Node Exporter
      ansible.builtin.systemd:
        name: node_exporter
        enabled: yes
        state: started
